name: Windows & Mac Build

on: [push, pull_request]

jobs:
  manylinux:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        compiler: ['gcc']

    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel pytest twine pillow
          
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Build wheels
        uses: joerick/cibuildwheel@v2.3.0
        env:
          CIBW_BUILD: |
            cp36-manylinux_x86_64 cp36-manylinux_i686	cp36-manylinux_aarch64 
            cp37-manylinux_x86_64 cp37-manylinux_i686 cp37-manylinux_aarch64 
            cp38-manylinux_x86_64 cp38-manylinux_i686 cp38-manylinux_aarch64 
            cp39-manylinux_x86_64 cp39-manylinux_i686 cp39-manylinux_aarch64 
            cp310-manylinux_x86_64 cp310-manylinux_i686 cp310-manylinux_aarch64
                
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
